sofsource/CMakeLists.txt, sofsource/R3BSofLinkDef.h
Was conflicting with r3bsource directory and leading to wrong rootmap file.
=> Rename the LinkDef file

CMakeLists.txt, README.md, macros/201410_Ubeam/SofATMapped.C, macros/201410_Ubeam/SofSciMapped.C, macros/201410_Ubeam/SofToFWMapped.C, macros/201607_Cbeam/SofSciMapped.C, macros/CMakeLists.txt, sofdata/R3BSofSciCalData.cxx, sofdata/README.md
Add information of the SOFIA set-up in the sofia/README.md file and update the installation procedure
Create the sofdata/README.md file to explain the data containers
Add the macros directory
Change CMakelist and README
=> Include <limits>

sofdata/R3BSofATMadcMappedData.cxx, sofdata/R3BSofATMadcMappedData.h, sofsource/R3BSofATMadcReader.cxx
New format for the AT, to follow the TClonesArray structure, as for the other detectors.
New reader to be compatible with this format.
Macro to produce root files didn't change
No analysis routine provided yet
=> New format mapped at

sofdata/R3BSofToFWMappedData.cxx, sofdata/R3BSofToFWMappedData.h, sofsource/CMakeLists.txt, sofsource/R3BSofLinkDef.h, sofsource/R3BSofToFWReader.cxx, sofsource/R3BSofToFWReader.h
add the reader for the SofToFW
=> modify the mapped data for the SofToFW (only one variable name)

macros/201410_Ubeam/SofATMapped.C, macros/201410_Ubeam/SofComRefMapped.C, macros/201410_Ubeam/SofDataVftx.C, macros/201410_Ubeam/SofToFWMapped.C, macros/201410_Ubeam/ViewFineTime.C, sofdata/CMakeLists.txt, sofdata/R3BSofATMadcMappedData.cxx, sofdata/R3BSofATMadcMappedData.h, sofdata/R3BSofComRefMappedData.cxx, sofdata/R3BSofComRefMappedData.h, sofdata/R3BSofMusicMdpp16MappedData.cxx, sofdata/R3BSofMusicMdpp16MappedData.h, sofdata/R3BSofSciCalData.cxx, sofdata/R3BSofSciCalData.h, sofdata/R3BSofSciMappedData.cxx, sofdata/R3BSofSciMappedData.h, sofdata/R3BSofToFWCalData.cxx, sofdata/R3BSofToFWCalData.h, sofdata/R3BSofToFWMappedData.cxx, sofdata/R3BSofToFWMappedData.h, sofsource/R3BSofLinkDef.h
Create a macro to read the VFTX root files and plot the fine time.
=> Debug macros to read mapped data from lmd files and create root files.

.gitignore, macros/201410_Ubeam/SofATMapped.C, macros/201410_Ubeam/SofComRefMapped.C, macros/201410_Ubeam/SofDataVftx.C, macros/201410_Ubeam/SofToFWMapped.C, macros/201410_Ubeam/SofTrimMapped.C, macros/201410_Ubeam/SofTwimMapped.C, macros/201410_Ubeam/ViewFineTime.C, sofsource/CMakeLists.txt, sofsource/R3BSofLinkDef.h, sofsource/R3BSofTwimMadcVftxReader.cxx, sofsource/R3BSofTwimMadcVftxReader.h, sofsource/ext_h101_softwim_madcvftx.h
Add the macros for the Twin-MUSIC when readout by ADC+VFTX
=> Add the reader for twin MUSIC when readout by MADC+VFTX

.gitignore, macros/201410_Ubeam/SofDataVftx.C, macros/201410_Ubeam/ViewSelectHitSofSci.C, macros/201410_Ubeam/ViewVftx.C, macros/201410_Ubeam/analysis01_unpack.C, macros/201410_Ubeam/analysis02_tcal.C, macros/201410_Ubeam/calib01_tcal_VFTX.C, sci/CMakeLists.txt, sci/R3BSofSciMapped2Tcal.cxx, sci/R3BSofSciMapped2Tcal.h, sci/R3BSofSciMapped2TcalPar.cxx, sci/R3BSofSciMapped2TcalPar.h, sci/SofSciLinkDef.h, sofdata/CMakeLists.txt, sofdata/R3BSofDataLinkDef.h, sofdata/R3BSofSciCalData.cxx, sofdata/R3BSofSciCalData.h, sofdata/R3BSofSciTcalData.cxx, sofdata/R3BSofSciTcalData.h, sofsource/R3BSofSciReader.cxx, sofsource/R3BSofSciReader.h, tcal/R3BSofTcalContFact.cxx, tcal/R3BSofTcalPar.cxx, tcal/R3BSofTcalPar.h
SofComRefMappedData and SofSciMappedData to SofSciTcalData
=> Include the step Mapped2Tcal for SofSci 

macros/geo/create_tofsofia_geo.C, macros/p2p/eventDisplay.C, macros/p2p/run_sim.C, twim/SofTWIMLinkDef.h
Modifications for sofia tof
Added removed lines
Update macro p2p
=> Update macros for p2p-fission simultations

mwpc0/CMakeLists.txt, mwpc0/R3BSofMwpc0CalPar.cxx, mwpc0/R3BSofMwpc0CalPar.h, mwpc0/R3BSofMwpc0Mapped2Cal.cxx, mwpc0/R3BSofMwpc0Mapped2Cal.h, mwpc0/SofMWPCLinkDef.h
Cosmetic changes in R3BSofMwpc0CalPar
=> Added (finally) mwpc0 classes to move data to cal level

mwpc3/R3BSofMwpc3CalPar.cxx, mwpc3/R3BSofMwpc3CalPar.h, mwpc3/R3BSofMwpc3ContFact.cxx, mwpc3/R3BSofMwpc3ContFact.h, mwpc3/R3BSofMwpc3Mapped2Cal.cxx, mwpc3/R3BSofMwpc3Mapped2Cal.h
They are not set in the CmakeLists because we need two more classes and it won't compile.
=> Added some classes.

macros/p2p/run_sim.C, sofonline/R3BSofAtOnlineSpectra.cxx, sofonline/R3BSofMwpc0OnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.h, sofonline/R3BSofTwimOnlineSpectra.cxx
=> Modified online classes to reset all histograms from the main online

mwpc1/CMakeLists.txt, mwpc1/R3BSofMwpc1Cal2Hit.cxx, mwpc1/R3BSofMwpc1Cal2Hit.h, mwpc1/R3BSofMwpc1CalPar.cxx, mwpc1/R3BSofMwpc1CalPar.h, mwpc1/R3BSofMwpc1ContFact.cxx, mwpc1/R3BSofMwpc1ContFact.h, mwpc1/R3BSofMwpc1Mapped2Cal.cxx, mwpc1/R3BSofMwpc1Mapped2Cal.h, mwpc1/R3BSofMwpc1Mapped2CalPar.cxx, mwpc1/R3BSofMwpc1Mapped2CalPar.h, mwpc1/SofMWPCLinkDef.h, mwpc3/SofMWPCLinkDef.h
- Added all classes for the Mwpc1
- Update CMakeLists for Mwpc1 and Mwpc3
- Update SofMWPCLinkDef for  Mwpc1 and Mwpc3
=> Added classes for the Mwpc1 and some checkings

macros/CMakeLists.txt, macros/p2p/eventDisplay.C, macros/p2p/runsim.C, mwpc0/CMakeLists.txt, mwpc0/R3BSofMwpc0ContFact.cxx, mwpc1/CMakeLists.txt, mwpc1/R3BSofMwpc1ContFact.cxx, mwpc2/CMakeLists.txt, mwpc2/R3BSofMwpc2ContFact.cxx, mwpc3/CMakeLists.txt, mwpc3/R3BSofMwpc3ContFact.cxx, sofdata/CMakeLists.txt, sofdata/R3BSofDataLinkDef.h, sofdata/tofwData/R3BSofTofWHitData.cxx, sofdata/tofwData/R3BSofTofWHitData.h, tofwall/CMakeLists.txt, tofwall/R3BSofTofWContFact.cxx, tofwall/R3BSofTofWContFact.h, tofwall/R3BSofTofWDigitizer.cxx, tofwall/R3BSofTofWDigitizer.h, tofwall/SofToFWLinkDef.h, twim/CMakeLists.txt, twim/R3BSofTwimContFact.cxx
Added geoPar containers for tracking detectors
Added R3BSofTofWHitData for the tof-wall
Added tof-wall digitizer
ToFW: Added transformation to local positions in the detector
=> Update macros with clang-format and containers for tracking detectors

macros/201911_online/eng_online.C, sofonline/R3BSofTwimOnlineSpectra.cxx, sofsource/R3BSofMwpcReader.cxx, sofsource/R3BSofMwpcReader.h, sofsource/R3BSofSciReader.cxx, sofsource/R3BSofSciReader.h, sofsource/R3BSofToFWReader.cxx, sofsource/R3BSofToFWReader.h, sofsource/R3BSofTrimReader.cxx, sofsource/R3BSofTrimReader.h, sofsource/R3BSofTwimReader.cxx
Cosmetic changes in the online macro
Update all the readers
=> Added the ToF-Wall to the online macro and some updates for twim online

macros/201911_online/eng_online.C, sofonline/R3BSofToFWOnlineSpectra.cxx, sofonline/R3BSofToFWOnlineSpectra.h, sofonline/R3BSofTwimOnlineSpectra.cxx, sofsource/R3BSofTwimReader.cxx, sofsource/R3BSofTwimReader.h
Modified twim reader to have two ref times
=> Added correlation ToF vs Twin-Music charge

macros/201911_online/eng_online.C, sofonline/R3BSofTwimOnlineSpectra.cxx, sofonline/R3BSofTwimOnlineSpectra.h
some modification in eng_online.C macro
=> Added new histograms to TWIM to see Esum vs DT

README.md, macros/p2psim/runsim.C, macros/s444/main_online.C, sofonline/CMakeLists.txt
Basic modification for readme
Resurrect again Califa hit finder
Modified cmake to take into account the new place of califa online class
Changes for me...
Added CALIFA container with the lookup table parameters for mapping
Update online macro for the s444 experiment
=> Basic modification for readme and update online macro for s444

mwpc/mwpc0/R3BSofMwpc0Cal2Hit.cxx, mwpc/mwpc0/R3BSofMwpc0Mapped2Cal.cxx, mwpc/mwpc0/R3BSofMwpc0Mapped2Cal.h, mwpc/mwpc1/R3BSofMwpc1Cal2Hit.cxx, mwpc/mwpc1/R3BSofMwpc1Mapped2Cal.cxx, mwpc/mwpc1/R3BSofMwpc1Mapped2Cal.h, mwpc/mwpc2/R3BSofMwpc2Cal2Hit.cxx, mwpc/mwpc2/R3BSofMwpc2Mapped2Cal.cxx, mwpc/mwpc2/R3BSofMwpc2Mapped2Cal.h, mwpc/mwpc3/R3BSofMwpc3Cal2Hit.cxx, mwpc/mwpc3/R3BSofMwpc3Mapped2Cal.cxx, mwpc/mwpc3/R3BSofMwpc3Mapped2Cal.h, sofana/CMakeLists.txt, sofdata/mwpcData/R3BSofMwpcCalData.cxx, sofdata/mwpcData/R3BSofMwpcCalData.h, sofdata/mwpcData/R3BSofMwpcMappedData.cxx, sofdata/mwpcData/R3BSofMwpcMappedData.h, sofdata/twimData/R3BSofTwimCalData.cxx, sofdata/twimData/R3BSofTwimCalData.h, sofdata/twimData/R3BSofTwimHitData.cxx, sofdata/twimData/R3BSofTwimHitData.h, sofdata/twimData/R3BSofTwimMappedData.cxx, sofdata/twimData/R3BSofTwimMappedData.h, sofonline/R3BAmsCorrelationOnlineSpectra.cxx, sofonline/R3BAmsCorrelationOnlineSpectra.h, sofonline/R3BSofOnlineLinkDef.h, twim/R3BSofTwimMapped2Cal.cxx, twim/R3BSofTwimMapped2Cal.h, twim/R3BSofTwimMapped2CalPar.cxx, twim/R3BSofTwimMapped2CalPar.h
Added to git the cmake for sofana
=> Changed from UShort to Int

macros/s444/main_online.C, sofonline/R3BAmsCorrelationOnlineSpectra.cxx, sofonline/R3BAmsCorrelationOnlineSpectra.h
Finished online task for AMS-CALIFA-Music correlations
=> Added musics and califa to ams correlation class

.gitignore, macros/s444/main_online.C, sofdata/CMakeLists.txt, sofdata/R3BSofDataLinkDef.h, sofdata/scalersData/R3BSofScalersMappedData.cxx, sofdata/scalersData/R3BSofScalersMappedData.h, sofonline/CMakeLists.txt, sofonline/R3BSofOnlineLinkDef.h, sofonline/R3BSofOnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.h, sofonline/R3BSofScalersOnlineSpectra.cxx, sofonline/R3BSofScalersOnlineSpectra.h, sofsource/CMakeLists.txt, sofsource/R3BSofLinkDef.h, sofsource/R3BSofScalersReader.cxx, sofsource/R3BSofScalersReader.h, sofsource/ext_h101_sofscalers.h
Reader of the scalers
Debug the reader
R3BSofScalersOnline
debugging ScalersOnline
change label of online spectra + debugging
modifying the main_online.C to get the scalers in
forgot to add a task in main_online
change the path in min_online before pull request
=> Include the Scalers for the online [Mapped Data only]

sci/R3BSofSciTcal2RawPosPar.cxx, sci/R3BSofSciTcal2RawPosPar.h, sci/R3BSofSciTcal2SingleTcal.cxx, sofdata/sciData/R3BSofSciSingleTcalData.h, sofonline/R3BSofSciOnlineSpectra.cxx, sofonline/R3BSofToFWOnlineSpectra.cxx, sofonline/R3BSofToFWOnlineSpectra.h, sofsource/R3BSofSciReader.cxx
include number of sci larger than 1
add multiplicity in tof in SofSciSingleTcalData.h
change the X raw pos in SofSci to have x increasing from LEFT to RIGHT
avoid the declaration of the number of detectors at several places
change the X position (increasing from right to left) in the online
=> find a bug in SofSciTcal2SingleTcal

macros/s444/main_online.C, mwpc/mwpc0/R3BSofMwpc0Cal2Hit.cxx, mwpc/mwpc0/R3BSofMwpc0Cal2Hit.h, mwpc/mwpc1/R3BSofMwpc1Cal2Hit.cxx, mwpc/mwpc1/R3BSofMwpc1Cal2Hit.h, mwpc/mwpc2/R3BSofMwpc2Cal2Hit.cxx, mwpc/mwpc2/R3BSofMwpc2Cal2Hit.h, mwpc/mwpc3/R3BSofMwpc3Cal2Hit.cxx, mwpc/mwpc3/R3BSofMwpc3Cal2Hit.h, sofonline/CMakeLists.txt, sofonline/R3BAmsCorrelationOnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.h, sofsource/CMakeLists.txt, sofsource/R3BSofLinkDef.h, sofsource/R3BSofWhiterabbitReader.cxx, sofsource/R3BSofWhiterabbitReader.h, sofsource/ext_h101_wrsofia.h
Update of online macro
Update of mwpc classes
Update of sofia online to display WR histograms
=> Added sofia WRs

macros/s444/main_online.C, sofdata/twimData/R3BSofTwimMappedData.cxx, sofdata/twimData/R3BSofTwimMappedData.h, sofsource/R3BSofTwimReader.cxx
=> add the pileup and overflow bits in the Twin Mapped Data

input/detectors_cfg.h, sci/CMakeLists.txt, sci/R3BSofSciTcal2RawPosPar.h, sofdata/CMakeLists.txt, sofonline/CMakeLists.txt, sofonline/R3BSofSciOnlineSpectra.cxx, sofonline/R3BSofSciOnlineSpectra.h
debugging
add RawTof versus RawPos spectra
debugging
=> add new online raw tof spectra for beam from the Tcal level

macros/s467/parameters/CalibParam.par, sci/R3BSofSciContFact.cxx, sci/R3BSofSciRawPosPar.h, sci/R3BSofSciRawTofPar.h, sci/R3BSofSciTcal2SingleTcal.cxx
Solve a gigantic and awfully stupid bug
=> add fake calibration parameters for the beam tof calibration preparation

sci/R3BSofSciTcal2SingleTcal.cxx
=> simplify the Tcal2SingleTcal

tcal/CMakeLists.txt, tcal/R3BSofiaProvideTStart.cxx, tcal/R3BSofiaProvideTStart.h, tcal/SofTcalLinkDef.h
Related to https://github.com/R3BRootGroup/R3BRoot/pull/334 
Note: This PR will only compile if the other is merged.
=> Provide TStart to R3BEventHeader

macros/s467/main_online.C, sofdata/trimData/R3BSofTrimMappedData.cxx, sofdata/trimData/R3BSofTrimMappedData.h, sofonline/CMakeLists.txt, sofonline/R3BSofOnlineLinkDef.h, sofonline/R3BSofOnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.h, sofonline/R3BSofTrimOnlineSpectra.cxx, sofonline/R3BSofTrimOnlineSpectra.h, sofsource/R3BSofTrimReader.cxx, sofsource/R3BSofTrimReader.h, sofsource/ext_h101_softrim.h
try to uderstand why spectra are empty
reader doesn't seem to read the data ...
still looking for the bug - unsuccessful
still trying to understand
remove cout
=> add Mapped data online for the Triple-MUSIC

sofonline/R3BSofAtOnlineSpectra.cxx, sofonline/R3BSofAtOnlineSpectra.h
=> Add 2D histo

macros/s467/parameters/CalibParam.par, mwpc/CMakeLists.txt, mwpc/mwpc3/R3BSofMwpc3Cal2Hit.cxx, mwpc/mwpc3/R3BSofMwpc3Cal2Hit.h
debugging
dubugging CalibParam.par
clang files
=> * Coding position matching between mwpc3 and tofwall

mwpc/mwpc3/R3BSofMwpc3Cal2Hit.cxx, mwpc/mwpc3/R3BSofMwpc3Cal2Hit.h
dubugging matching between tofwall and mwpc3
=> updating the matching part between tofwall and mwpc3

macros/s455/main_online.C, macros/s455/parameters/CalibParam.par, macros/s467/parameters/CalibParam.par, sofonline/CMakeLists.txt, sofonline/R3BSofOnlineLinkDef.h, sofonline/R3BSofOnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.h, sofonline/R3BSofTrackingFissionOnlineSpectra.cxx, sofonline/R3BSofTrackingFissionOnlineSpectra.h
=> Added online for tracking of fission fragments

macros/s455/calibration/softrim_dtoffset.C, macros/s455/main_online.C, macros/s455/parameters/CalibParam.par, sofdata/trimData/R3BSofTrimHitData.cxx, sofdata/trimData/R3BSofTrimHitData.h, sofonline/R3BSofTrimOnlineSpectra.cxx, sofsource/R3BSofTwimReader.cxx, sofsource/R3BSofTwimReader.h, trim/R3BSofTrimCal2Hit.cxx, trim/R3BSofTrimCal2Hit.h, trim/R3BSofTrimCalculateDriftTimeOffsetPar.cxx, trim/R3BSofTrimCalculateDriftTimeOffsetPar.h
add the calculation of Ebeta per section in Cal2Hit
simplify main_online.C
change the binning of the energy histograms to fit the 16 bits ADC
DT offset calculation with Zpos in GeoPar from middle of detectors
=> Triple-MUSIC at HIT level

macros/s455/main_online.C, sofonline/R3BSofTrimOnlineSpectra.cxx
main_online with the new unpacker 202103_s455
=> Remove return kFATAL if TrimHitData are not found.

sofdata/twimData/R3BSofTwimMappedData.h, sofonline/R3BSofTofWOnlineSpectra.cxx, sofonline/R3BSofTwimOnlineSpectra.cxx, sofonline/R3BSofTwimOnlineSpectra.h, sofsource/R3BSofTwimReader.cxx, sofsource/R3BSofTwimReader.h
add only a comment for the user (Twin-MUSIC is 0-based)
debug the online for Ypos in TofW calculated from Tcal
add mult histos and T-Ttrig histo to check the searching window
=> Debug TwimReader

macros/s455/main_online.C, sofonline/R3BAmsCorrelationOnlineSpectra.cxx, sofonline/R3BAmsCorrelationOnlineSpectra.h, sofonline/R3BSofAtOnlineSpectra.cxx, sofonline/R3BSofOnlineSpectra.cxx, sofonline/R3BSofTofWOnlineSpectra.cxx, sofonline/R3BSofTwimOnlineSpectra.cxx, sofsource/R3BSofTwimReader.cxx
New range for energy histo in twim
=> Update onlines for twim and tof wall

macros/s455/parameters/CalibParam.par, sofonline/R3BSofMwpcOnlineSpectra.cxx, sofonline/R3BSofMwpcOnlineSpectra.h
cosmetics
Update
New range for energy histo in twim
Update Twim Reader
Update stream-server for daq
Update sci parameters
Solved problem with the reset of mwpc histo
=> MWPC : add number of pads per event histogram from Audrey

macros/status/status_online.C, sofonline/R3BSofStatusOnlineSpectra.cxx, sofonline/R3BSofStatusOnlineSpectra.h, tofwall/R3BSofTofWSingleTCal2Hit.cxx
Change wr histograms to thstack style
=> Added AMS WR to the status online

sofsource/CMakeLists.txt, sofsource/R3BSofCorrmReader.cxx, sofsource/R3BSofCorrvReader.cxx, sofsource/R3BSofLinkDef.h, sofsource/R3BVftxTrigReader.cxx
debug SOFCORRx_yyM values can be 0 or 1
=> Debug correlation readers while running on-line

macros/s455Up2p/parameters/CalibParam.par, macros/s515/main_online.C, macros/s515/parameters/CalibParam_onesci.par, macros/s515/parameters/CalibParam_twosci.par
=> Update parameters for s455 p2p-fission

macros/s515/main_online.C, sofonline/CMakeLists.txt, sofonline/R3BSofOnlineLinkDef.h, sofonline/R3BSofSciVsPspxOnlineSpectra.cxx, sofonline/R3BSofSciVsPspxOnlineSpectra.h
Added online to correlate pspx and tof-S2-Cave
=> Added online to see correlations between pspx and s2-cave-c tof

macros/s515/main_online.C, sofonline/R3BSofSciVsPspxOnlineSpectra.cxx
update
Changed paths in the online macro
=> Update online macro for s515

macros/s455Up2p/cal_offline.C, macros/s455Up2p/unpack_offline.C, sofsource/R3BSofWhiterabbitReader.cxx
Update macros
update macro s455
=> Examples to start with the parameter reader

macros/p2psim/runsim.C, macros/p2psim/s455_setup.par, macros/s455Up2p/unpack/cal_offline.C, macros/s455Up2p/unpack/unpack_offline.C
=> Update s455p2p parameters for simulation

sofana/R3BSofFrsAnalysis.cxx
Fix bugs to handle events with only S2 or S8 timing available.
=> Bug fix of the vector in R3BSofFrsAnalysis
